const skillBridgeProject = {
  id: 'skillbridge',
  name: 'SkillBridge',
  category: 'FULL-STACK / E-LEARNING / AI',
  status: 'IN PROGRESS',
  description: 'Full-Stack E-Learning & Training Platform connecting learners and training centers in Tunisia.',
  liveUrl: 'https://kaleidoscopic-parfait-dbaf5a.netlify.app/',
  technologies: ['React.js', 'Tailwind CSS', 'Node.js', 'Express.js', 'MongoDB', 'Socket.IO', 'JWT', 'Supabase', 'n8n'],
  featuredTechnologies: ['React.js', 'Tailwind CSS', 'Node.js', 'Express.js', 'MongoDB', 'JWT', 'Socket.IO', 'Supabase', 'n8n'],
  stackGroups: [
    { label: 'Frontend', items: ['React.js', 'React Router', 'Tailwind CSS'] },
    { label: 'Backend', items: ['Node.js', 'Express.js', 'REST API'] },
    { label: 'Database', items: ['MongoDB'] },
    { label: 'Authentication & Security', items: ['JWT', 'Role-Based Access Control', 'Protected Routes'] },
    { label: 'Real-Time', items: ['Socket.IO'] },
    { label: 'Storage', items: ['Supabase Storage', 'Private Buckets', 'Secure File Handling'] },
    { label: 'Communication', items: ['Nodemailer'] },
    { label: 'AI & Automation', items: ['n8n', 'Webhooks', 'API Integrations', 'AI Agent'] },
    { label: 'Deployment', items: ['Netlify', 'Render'] },
    { label: 'Version Control', items: ['Git', 'GitHub'] },
  ],
  engineeringSkills: ['Frontend Development', 'React Architecture', 'Responsive UI/UX', 'REST API Development', 'Backend Development', 'Database Design', 'Authentication', 'Authorization', 'Role-Based Access Control', 'Real-Time Web Applications', 'WebSocket Communication', 'File Storage', 'PDF Generation', 'API Integration', 'Email Services', 'AI Automation', 'Webhooks', 'Deployment', 'Git / GitHub', 'Full-Stack Architecture'],
  securityPoints: ['JWT-based authentication', 'Protected routes', 'Role-Based Access Control', 'Learner / Training Center / Admin authorization', 'Password recovery', 'Secure file access', 'Private Supabase Storage bucket', 'Backend API protection'],
  backendResponsibilities: ['Authentication', 'Authorization', 'Users', 'Training centers', 'Formations', 'Reservations', 'Notifications', 'Messaging', 'Certificates', 'API communication'],
  deployment: [{ label: 'Frontend', value: 'Netlify' }, { label: 'Backend', value: 'Render' }, { label: 'Version Control', value: 'Git + GitHub' }],
  features: [
    'Multi-role platform',
    'Real-time messaging',
    'Secure authentication',
    'Training management',
    'AI-assisted support',
    'PDF certificates',
  ],
  highlights: [
    { number: '01', title: 'Multi-Role Architecture', text: 'Learner, Training Center and Administrator environments with role-based access control.' },
    { number: '02', title: 'Real-Time Communication', text: 'Real-time messaging and notifications using Socket.IO.' },
    { number: '03', title: 'Secure Authentication', text: 'JWT-based authentication and protected role-specific routes.' },
    { number: '04', title: 'Training Management', text: 'Training discovery, filtering, reservations, sessions, attendance and progress tracking.' },
    { number: '05', title: 'Certification', text: 'PDF certificate generation and certification management.' },
    { number: '06', title: 'Secure File Storage', text: 'Private Supabase Storage for persistent platform files and attachments.' },
    { number: '07', title: 'AI & Automation', text: 'n8n-based AI workflow integrated for intelligent user assistance and selected automation.' },
  ],
};

export default skillBridgeProject;
